---
spring:
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  application:
    name: order-service
  datasource:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/fescar?useSSL=false&serverTimezone=UTC
    username: root
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    #每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
    lease-renewal-interval-in-seconds: 1
    #告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-expiration-duration-in-seconds: 2
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
logging:
  level:
    org:
      springframework:
        cloud:
          alibaba:
            seata:
              web: debug
    io:
      seata: debug
feign:
  hystrix:
    enabled: true

