server:
  port: 8761
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
    
spring:
  profiles:
    active: dev
    

management:
  endpoint:
    # 启用pause端点
    pause:
      enabled: true
    # 启用restart端点，之所以要启用restart端点，是因为pause端点的启用依赖restart端点的启用。详见：https://cloud.spring.io/spring-cloud-static/Finchley.SR2/single/spring-cloud.html#_endpoints
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: pause,restart    


